# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate distances between a matrix of positive-definite covariance matrices concatenated
#' horizontally
#'
#' @param samples posterior samples matrix, arranged by host and concatenated across columns
#' @param n_indiv number of hosts
#' @param n_samples_per number of samples per host
#' @details Dimensions of the samples matrix are D rows x DN columns where D = no. of features
#' and N = no. of samples
#' @return distance
Riemann_dist_samples <- function(samples, n_indiv, n_samples_per) {
    .Call('_ROL_Riemann_dist_samples', PACKAGE = 'ROL', samples, n_indiv, n_samples_per)
}

#' Calculate distances between positive-definite covariance matrices
#'
#' @param A matrix 1
#' @param B matrix 2
#' @return distance
Riemann_dist_pair <- function(A, B) {
    .Call('_ROL_Riemann_dist_pair', PACKAGE = 'ROL', A, B)
}

